if(EXISTS "/home/kassym/dynagox/dynagox_cpp/implement/build-linux/tests/tests-b12d07c_tests.cmake")
  include("/home/kassym/dynagox/dynagox_cpp/implement/build-linux/tests/tests-b12d07c_tests.cmake")
else()
  add_test(tests_NOT_BUILT-b12d07c tests_NOT_BUILT-b12d07c)
endif()
